### PR TITLE
Use golang `expvar` pkg for collecting internal metrics; more logs

### PR DESCRIPTION
**Pull request by arvenil**
Just more logs for QAN `mongo` but also switch to https://golang.org/pkg/expvar/ for collecting metrics. Still far from perfect but works at the moment.

Also status line for profiler shows more human readable info e.g. `Profiling enabled for all queries (ratelimit: 1)` or `Profiling disabled. Please enable profiling with "db.setProfilingLevel(2)" (https://docs.mongodb.com/manual/tutorial/manage-the-database-profiler/).`

### CODE REVIEW

**Comment by AlekSi** [comment]
Why use `expvar` and not Prometheus metrics?

**Comment by arvenil** [comment]
@AlekSi I would love to have whole agent exposing metrics to prometheus, but for that we should create separate jira issue (and really I was asking for this looooong time ago:)).

`expvar` here doesn't really expose any metrics, exposing metrics would require more testing. I needed some thread-safe basic types for internal metrics that are converted to internal `status` that is visible in UI. So I'm using only expvar types. Otherwise the old approach was to get `string` status (metric), convert it to int, increment, convert to string, set status. Changing that to prometheus metrics shouldn't be an issue - introducing prometheus in agent will be more problematic.

**Comment by AlekSi** [comment]
> `expvar` here doesn't really expose any metrics

Unfortunately, that's not true: `expvar` exposes them by default at `/debug/vars` in default server mux, which is used in LocalInterface. That's the biggest problem with this package.

> I needed some thread-safe basic types for internal metrics

What about `atomic.Value`?

**Comment by arvenil** [comment]
>> expvar here doesn't really expose any metrics

> Unfortunately, that's not true: expvar exposes them by default at /debug/vars in default server mux, which is used in LocalInterface. That's the biggest problem with this package.

It registers http handler - correct. However to expose it as `/debug/vars` you need to first start http web server. Right or I'm wrong?

I know, I saw this. But as long as it doesn't expose http protocol with `/debug/vars` then it works for me.

>> I needed some thread-safe basic types for internal metrics

> What about atomic.Value?

Then you need type assertion for every read. 

If this:
```go
func init() {

	http.HandleFunc("/debug/vars", expvarHandler)

	Publish("cmdline", Func(cmdline))

	Publish("memstats", Func(memstats))

}
```
bothers you I can just copy & paste the types I need. I was going to write them by myself but then realized `expvar` is providing what i need. I can also fork this and create new package without this `init` script. In any case this is really trivial thing that I hope will go away one day with some proper instrumentation in whole agent.

**Comment by AlekSi** [comment]
> However to expose it as /debug/vars you need to first start http web server. Right or I'm wrong?

You are right. We had `http.ListenAndServe` with default mux in `agent/status.go`. My local copy was outdated, sorry about the confusion.

**Review by AlekSi — APPROVED** [review]
LGTM.

**Pull request merged**
